### ISSUE TITLE
Proposal: Shipping Docker CLI for Windows

### ISSUE THREAD

**Issue by ahmetalpbalkan** [boot2docker/windows-installer#80]
We have a full **Docker command-line interface for Windows** coming up with the Docker 1.6 release and people can now use docker.exe on their Windows machines without ssh-ing to the boot2docker VM.

This proposal is about modifying the Boot2Docker Windows Installer so that people don't need any other package manager or download something to get going with Docker on Windows.

### tl;dr gimme the ROADMAP

- `boot2docker-cli`: (https://github.com/boot2docker/boot2docker-cli/pull/356)
    - [x] start/shellinit: remove windows-specific warning saying docker cli is does not exist yet.
    - [x] shellinit: add a note to advise `set VAR=VAL` on cmd and `$env:VAR = "VAL"` in powershell 
        - [x] see if it's feasible to execute shellinit in cmd/powershell (requires ssh.exe in PATH), if so, update `printExport()`.
- `windows-installer`:
    - [x] bundle `docker.exe` within the installer (#82)
    - [x] fix installer message to say "Add docker.exe and boot2docker.exe to PATH"  (#86)
    - [x] fix `start.sh` to not to ssh in the vbox VM by default (#88)
        - [ ] suppress git bash motd
- `docs`:
    - [x] update docs in `docker/docs` to reflect the changes to b2d installation (https://github.com/docker/docker/pull/11875)
    - [ ] shoot a new installation video

### Updating boot2docker installer

I'm proposing to edit the boot2docker windows installer to:

1. Bundle `docker.exe` cli binary in the installer.
1. Install it to the same dir as `boot2docker.exe` (e.g. `c:\program files\boot2docker\...`)
1. Therefore, have docker.exe in `%PATH%`.
1. Update the UX around `boot2docker up` command and the start menu item "Boot2Docker Start" so that it does not ssh into the b2d VM by default on windows (because user does not need to).
    - This will remove the ssh.exe in `%PATH%` requirement on windows.

### Package Manager Installations

We are planning to distribute docker CLI for Windows mainly with boot2docker installation, however windows has several package managers, like Chocolatey and OneGet. I will be creating docker packages for those and will be maintaining for a few releases and Docker folks can take over any time. (chatted w/ Sven about this)

These package managers will download from an URL (like http://get.docker.com/builds/Windows/x86_64/docker-1.6.0.exe), and add it to `%PATH%` env var so that people can just use docker.exe CLI without boot2docker or anything. This will be the suggested way to install just the CLI.

Since both b2d and package managers will add the CLI binary (docker.exe) to `%PATH%`, documentation must suggest using one or the other; not both. For instance, if user has different versions of docker.exe in `%PATH%`, the look path precedence will come into the picture and in this case we will assume user knows what they are doing and not get in their way.

### Documentation

I will be writing/updating docs about the new installation methods as well as the existing Boot2Docker method. I'm also volunteering to shoot video tutorials about this. (https://github.com/docker/docker/issues/11192)

Also, while updating the `b2d up` cmd and the "Boot2Docker Start" batch script, we may need to add additional instructions to help users understand how to use the docker.exe. I will revisit those as well.

### Conclusion

It appears like after the freeze (in 2 days) we will have some 1.6 rc binaries. I will update the installer and start.sh script to reflect the changes and send a pull request.

Thanks if you've read this far, please let me know what you think.

--------------
cc: @SvenDowideit @tianon @icecrime @tiborvass @johngossman

**Comment by tianon** [comment]
> Download `docker.exe` binary from `get.docker.com`

As long as you don't literally mean that the installer itself will be doing the downloading, I'm +1 and was already planning on including this.

I'm +1 to having `start.sh` not SSH directly into the VM by default, too.

**Comment by ahmetalpbalkan** [comment]
@tianon 

> As long as you don't literally mean that the installer itself will be doing the downloading

I guess we can take OS X as an example, I don't know how we deliver the docker CLI binary with the installation. Do we download in the installer or bundle with the installer?

**Comment by tianon** [comment]
It's currently bundling, especially so that when people download
"boot2docker 1.5.0", they get Docker 1.5.0, which is how it works here too.

**Comment by ahmetalpbalkan** [comment]
@tianon ok I was obviously speculating about how it works. I'll read the scripts, thanks!

**Comment by tianon** [comment]
:heart:

**Comment by SvenDowideit** [comment]
I just ran `make docs` from my windows box, and its very nice - thank you :)

**Comment by ahmetalpbalkan** [comment]
Oh forgot to close this lol
